title: Digitally Engaged Learning Conference 2022
# Versioning
current_version: 1.5.0
foundation_version: 6.0.0
future: true

social:
  email:
  facebook:
  twitter: DELconference

# Dependencies
markdown: kramdown
#Syntax Highlighter
#highlighter:        pygments

plugins:
  # Other plugins go here
 - jekyll-paginate

paginate: 2
paginate_path: /page:num/

# Permalinks
permalink: pretty

# Server
# source:             ./source Git Pages overrides this variable
# destination:        ./static

port: 9002
url:  # the base hostname & protocol for your site
baseurl: "/2022"
repository: del-conference/2022
# exclude this stuff when building the static site
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock", "vendor/bundle"]

## CUSTOM VARS

#ga_id:             ##-########-###
site_name: Digitally Engaged Learning Conference 2022
site_description:
site_copyright: Copyright (c) 2022
site_url: https://del-conference.github.io/2022/
site_email:
site_phone:

# Assets
# We specify the directory for s3-website so we can use @imports.
sass:
  sass_dir: ./assets/stylesheets
  style: :compressed

# Collections
collections:
  programs:
    output: true
  events:
    output: true
  team:
    output: true
  front-page-callouts:
    output: false
  page-sections:
    output: false
  layout-sections:
    output: false
  #ThrivingAG
  news-activities:
    output: true
  people:
    output: false
  research:
    output: true
    permalink: /research/:title/
  outreach-engagement:
    output: true
    permalink: /outreach-engagement/:title/
  courses:
    output: false
  objective-teams:
    output: false
  stakeholder-groups:
    output: false